let number = [2, 3, 1, 54, 23, 1, 5];
console.log(number);
console.log(number.sort());
console.log(number.pop());
console.log(number);
console.log(number.push("Prashant"));
console.log(number);
console.log(number.shift());
console.log(number.unshift());
console.log(number.length);
console.log(number.replace("Prashant","Poojary"));
console.log(number);

let name = "Prashant Poojary is doing MCA";
console.log(name.indexOf("MCA"));
console.log(name.lastIndexOf("is"));
console.log(name.slice(1, 4));
console.log(name.length);
let change=name.replace("Prashant","Suresh");
console.log(change);